const $=id=>document.getElementById(id); let quoteType="single", lastCalc=null;
const money=v=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v||0));
const roundUp=(v,i)=>Math.ceil(v/i)*i;
function populateSelect(id,obj){const el=$(id);el.innerHTML="";Object.entries(obj).forEach(([k,d])=>{const o=document.createElement("option");o.value=k;o.textContent=d.label;el.appendChild(o)})}
function setup(){populateSelect("frameSize",PRICES.steel.frame);populateSelect("postSize",PRICES.steel.posts);populateSelect("hinges",PRICES.hardware.hinges);populateSelect("latch",PRICES.hardware.latches);PRICES.cladding.ekodeck.colours.forEach(c=>$("ekodeckColour").add(new Option(c,c)));PRICES.cladding.cypressPickets.lengths.forEach(n=>$("picketLength").add(new Option(`${n}mm`,n)));PRICES.cladding.colorbond.profiles.forEach(p=>$("colorbondProfile").add(new Option(p,p)));$("powderCost").value=PRICES.finishing.powderCoatTypical;fillCompany();}
function fillCompany(){const c=PRICES.company;$("quoteCompanyName").textContent=c.name;$("quoteCompanyAddress").textContent=c.address;$("quoteCompanyContact").textContent=`${c.phone} | ${c.email}`;$("quoteCompanyWeb").textContent=c.website;$("quoteCompanyAbn").textContent=`ABN ${c.abn}`}
function validateField(el){if(!el.classList.contains("required-field"))return;let ok=String(el.value||"").trim()!=="";if(el.id==="projectNumber")ok=/^\d{6}$/.test(el.value);if(el.type==="email")ok=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(el.value);el.classList.toggle("field-ok",ok)}
function validateAll(){document.querySelectorAll(".required-field").forEach(validateField)}
function setQuoteType(t){quoteType=t;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.type===t));calculate()}
function updateSticky(){$("stickyCustomerName").textContent=$("customerName").value.trim()||"New quote"}
function updateMeasurements(auto=true){const cw=Number($("cavityWidth").value||0),ch=Number($("cavityHeight").value||0),gl=Number($("gapLeft").value||0),gr=Number($("gapRight").value||0),gb=Number($("gapBottom").value||0);const w=Math.max(0,cw-gl-gr),h=Math.max(0,ch-gb);$("calcGateWidth").textContent=`${w} mm`;$("calcGateHeight").textContent=`${h} mm`;if(auto){$("gateWidth").value=w;$("gateHeight").value=h}}
function conditional(){const c=$("claddingType").value;$("ekodeckOptions").classList.toggle("hidden",c!=="ekodeck");$("cypressOptions").classList.toggle("hidden",c!=="cypress");$("picketOptions").classList.toggle("hidden",c!=="cypressPickets");$("colorbondOptions").classList.toggle("hidden",c!=="colorbond");$("customCladdingOptions").classList.toggle("hidden",c!=="custom");const f=$("fixingType").value;$("concreteOptions").classList.toggle("hidden",!(f==="concreted"||f==="concreteBrick"));$("boltOptions").classList.toggle("hidden",!(f==="brick"||f==="concreteBrick"));$("powderOptions").classList.toggle("hidden",!$("powderCoat").checked);$("paintOptions").classList.toggle("hidden",!($("claddingType").value==="cypress"&&$("cypressFinish").value==="painted"));}
function frameRate(){const s=$("frameSize").value;return s==="custom"?Number($("customFrameRate").value||0):PRICES.steel.frame[s].ratePerM}
function postRate(){const s=$("postSize").value;return s==="custom"?Number($("customPostRate").value||0):PRICES.steel.posts[s].ratePerM}
function frameLabel(){const s=$("frameSize").value;return s==="custom"?($("customFrameLabel").value||"Custom frame"):PRICES.steel.frame[s].label}
function postLabel(){const s=$("postSize").value;return s==="custom"?($("customPostLabel").value||"Custom posts"):PRICES.steel.posts[s].label}
function claddingCalc(wM,hM){const type=$("claddingType").value,gap=Number($("boardGap").value||0);if(type==="colorbond"){const area=wM*hM;return{qty:1,lm:0,cost:area*PRICES.cladding.colorbond.ratePerM2,desc:`Colorbond ${$("colorbondProfile").value}${$("colorbondNotes").value.trim()?`, ${$("colorbondNotes").value.trim()}`:""}`}}let boardWidth=0,rate=0,desc="";if(type==="ekodeck"){boardWidth=67;rate=PRICES.cladding.ekodeck.ratePerM;desc=`Ekodeck screening 67x15mm, ${$("ekodeckColour").value}`}if(type==="cypress"){boardWidth=67;rate=PRICES.cladding.cypress.ratePerM;desc=`Cypress 67x15mm, ${$("cypressFinish").value}`}if(type==="cypressPickets"){boardWidth=PRICES.cladding.cypressPickets.boardWidthMm;rate=PRICES.cladding.cypressPickets.ratePerM;desc=`Cypress pickets, ${$("picketLength").value}mm stock length`}if(type==="merbau90"){boardWidth=90;rate=PRICES.cladding.merbau90.ratePerM;desc=PRICES.cladding.merbau90.label}if(type==="merbau140"){boardWidth=140;rate=PRICES.cladding.merbau140.ratePerM;desc=PRICES.cladding.merbau140.label}if(type==="custom"){boardWidth=Number($("customBoardWidth").value||70);rate=Number($("customCladdingRate").value||0);desc=$("customCladdingName").value||"Custom cladding"}const qty=Math.max(0,Math.ceil((wM*1000)/(boardWidth+gap)));const lm=qty*hM;return{qty,lm,cost:lm*rate,desc}}
function calculate(){conditional();validateAll();updateSticky();const w=Number($("gateWidth").value||0)/1000,h=Number($("gateHeight").value||0)/1000;let frameM=(2*w)+(2*h);if(quoteType==="double")frameM=(2*w)+(4*h);if(quoteType==="slider")frameM=(2*w)+(2*h);frameM+=Number($("extraFrameLengthMm").value||0)/1000;const frameStocks=Math.ceil(frameM/8),frameWaste=Math.max(0,frameStocks*8-frameM);const postM=Number($("postCount").value||0)*Number($("postLengthMm").value||0)/1000;const postStocks=postM>0?Math.ceil(postM/8):0,postWaste=Math.max(0,postStocks*8-postM);const clad=claddingCalc(w,h);$("frameMetres").textContent=`${frameM.toFixed(2)} m`;$("frameStockLengths").textContent=frameStocks;$("frameWaste").textContent=`${frameWaste.toFixed(2)} m`;$("postMetres").textContent=`${postM.toFixed(2)} m`;$("postStockLengths").textContent=postStocks;$("postWaste").textContent=`${postWaste.toFixed(2)} m`;$("claddingQty").textContent=clad.qty;$("claddingMetres").textContent=`${clad.lm.toFixed(2)} m`;$("totalMaterialMetres").textContent=`${(frameM+postM+clad.lm).toFixed(2)} m`;const frameCost=frameM*frameRate(),postCost=postM*postRate();const hinges=PRICES.hardware.hinges[$("hinges").value].price,latch=PRICES.hardware.latches[$("latch").value].price;const fix=$("fixingType").value,concrete=(fix==="concreted"||fix==="concreteBrick")?Number($("concreteBags").value||0)*PRICES.fixings.concreteBag:0,bolts=(fix==="brick"||fix==="concreteBrick")?Number($("boltCount").value||0)*PRICES.fixings.boltEach:0,powder=$("powderCoat").checked?Number($("powderCost").value||0):0,paintMat=($("claddingType").value==="cypress"&&$("cypressFinish").value==="painted")?Number($("paintMaterialCost").value||0):0;const materials=frameCost+postCost+clad.cost+hinges+latch+concrete+bolts+powder+paintMat;const groundH=(fix==="concreted"||fix==="concreteBrick")?Number($("groundHours").value||0):0,paintH=($("claddingType").value==="cypress"&&$("cypressFinish").value==="painted")?Number($("paintHours").value||0):0,hours=Number($("fabricationHours").value||0)+Number($("installationHours").value||0)+groundH+paintH,labour=hours*PRICES.business.labourRate;const travelKm=Math.max(0,Number($("travelKm").value||0)-PRICES.business.includedTravelKm),travel=travelKm*PRICES.business.travelRatePerKm,other=Number($("otherCosts").value||0),markup=materials*PRICES.business.materialMarkup,ex=materials+labour+travel+other+markup,gst=ex*PRICES.business.gst,inc=ex+gst,final=roundUp(inc,PRICES.business.roundTo);lastCalc={frameM,postM,clad,materials,labour,travel,other,markup,ex,gst,inc};$("materialsTotal").textContent=money(materials);$("labourTotal").textContent=money(labour);$("travelTotal").textContent=money(travel);$("markupTotal").textContent=money(markup);$("gstTotal").textContent=money(gst);$("incGstTotal").textContent=money(inc);if(!$("finalPrice").dataset.manual)$("finalPrice").value=final;updateProfit();createQuote();}
function updateProfit(){if(!lastCalc)return;const finalInc=Number($("finalPrice").value||0),finalEx=finalInc/(1+PRICES.business.gst),profit=finalEx-(lastCalc.materials+lastCalc.labour+lastCalc.travel+lastCalc.other);$("profitTotal").textContent=money(profit);$("quotePrice").textContent=money(finalInc)}
function installText(){const f=$("fixingType").value;if(f==="concreted")return`Posts concreted into ground using ${$("concreteBags").value} bag(s) of concrete.`;if(f==="brick")return`Fixed to brickwork using ${$("boltCount").value} x ${$("boltType").value}.`;if(f==="concreteBrick")return`Posts concreted into ground and fixed to brickwork using ${$("boltCount").value} x ${$("boltType").value}.`;return"Gate fitted to existing structure."}
function createQuote(){const types={single:"single gate",double:"double / driveway gate",slider:"sliding gate"},clad=lastCalc?lastCalc.clad.desc:"";let s=`Supply and install custom ${types[quoteType]}.\n\nOriginal cavity:\n${$("cavityWidth").value}mm wide x ${$("cavityHeight").value}mm high\n\nProposed gate:\n${$("gateWidth").value}mm wide x ${$("gateHeight").value}mm high\nClearances: ${$("gapLeft").value}mm left, ${$("gapRight").value}mm right, ${$("gapBottom").value}mm under gate.\n\nFrame and posts:\n${frameLabel()} frame\n${$("postCount").value} x ${postLabel()} post(s)\n\nCladding:\n${clad}\n\nHardware:\n${PRICES.hardware.hinges[$("hinges").value].label}\n${PRICES.hardware.latches[$("latch").value].label}\n\nInstallation:\n${installText()}`;if($("powderCoat").checked)s+=`\n\nSteel finish:\nPowder coated${$("powderColour").value.trim()?` ${$("powderColour").value.trim()}`:""}.`;if($("claddingType").value==="cypress")s+=`\n\nTimber finish:\n${$("cypressFinish").value==="painted"?`Painted${$("paintColour").value.trim()?` ${$("paintColour").value.trim()}`:""}.`:"Raw / unpainted."}`;$("quoteDescription").value=s;$("quoteProject").textContent=$("projectNumber").value;$("quoteCustomer").textContent=$("customerName").value;$("quoteAddress").textContent=$("siteAddress").value;updateProfit()}
function collect(){return{id:$("projectNumber").value||Date.now().toString(),savedAt:new Date().toISOString(),type:quoteType,form:Object.fromEntries([...document.querySelectorAll("input,select,textarea")].filter(e=>e.id).map(e=>[e.id,e.type==="checkbox"?e.checked:e.value]))}}
function saveQuote(){calculate();const q=collect(),arr=JSON.parse(localStorage.getItem("jtlaGateQuotes")||"[]"),i=arr.findIndex(x=>x.id===q.id);if(i>=0)arr[i]=q;else arr.unshift(q);localStorage.setItem("jtlaGateQuotes",JSON.stringify(arr));renderSaved()}
function renderSaved(){const arr=JSON.parse(localStorage.getItem("jtlaGateQuotes")||"[]"),c=$("savedQuotes");if(!arr.length){c.innerHTML='<p class="muted">No saved quotes yet.</p>';return}c.innerHTML=arr.map(q=>`<div class="saved-row"><div><strong>${q.id}</strong><br><span>${q.form.customerName||"Unnamed"}</span></div><div><button class="small" data-load="${q.id}">Open</button> <button class="small danger" data-del="${q.id}">Delete</button></div></div>`).join("");c.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>loadQuote(b.dataset.load));c.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>deleteQuote(b.dataset.del))}
function loadQuote(id){const q=JSON.parse(localStorage.getItem("jtlaGateQuotes")||"[]").find(x=>x.id===id);if(!q)return;quoteType=q.type;Object.entries(q.form).forEach(([id,v])=>{const e=$(id);if(!e)return;e.type==="checkbox"?e.checked=!!v:e.value=v});document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.type===quoteType));conditional();calculate();scrollTo({top:0,behavior:"smooth"})}
function deleteQuote(id){localStorage.setItem("jtlaGateQuotes",JSON.stringify(JSON.parse(localStorage.getItem("jtlaGateQuotes")||"[]").filter(x=>x.id!==id)));renderSaved()}
function sms(){calculate();const msg=`Hi ${$("customerName").value||"there"},\n\nThanks for the opportunity to quote your gate.\n\nJTLA Project ${$("projectNumber").value}\nTotal: ${money($("finalPrice").value)} including GST.\n\nRegards,\nJody\nJT Landscape Architect`;location.href=`sms:${$("customerPhone").value}?body=${encodeURIComponent(msg)}`}
function email(){calculate();const body=`Hi ${$("customerName").value||"there"},\n\nThank you for the opportunity to provide a quote.\n\n${$("quoteDescription").value}\n\nTotal: ${money($("finalPrice").value)} including GST.\n\nRegards,\nJody\nJT Landscape Architect`;location.href=`mailto:${$("customerEmail").value}?subject=${encodeURIComponent(`JTLA Quote ${$("projectNumber").value}`)}&body=${encodeURIComponent(body)}`}
function newQuote(){location.reload()}
document.addEventListener("DOMContentLoaded",()=>{setup();document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>setQuoteType(b.dataset.type));["cavityWidth","cavityHeight","gapLeft","gapRight","gapBottom"].forEach(id=>$(id).addEventListener("input",()=>{updateMeasurements(true);calculate()}));document.querySelectorAll("input,select,textarea").forEach(e=>{e.addEventListener("input",()=>{validateField(e);if(e.id==="customerName")updateSticky();if(e.id==="finalPrice"){e.dataset.manual="1";updateProfit();return}calculate()});e.addEventListener("change",()=>{validateField(e);conditional();calculate()})});$("calculateBtn").onclick=calculate;$("saveBtn").onclick=saveQuote;$("smsBtn").onclick=sms;$("emailBtn").onclick=email;$("printBtn").onclick=()=>{calculate();print()};$("newQuoteBtn").onclick=newQuote;updateMeasurements(true);conditional();calculate();renderSaved();validateAll()});
